command: ['npm', 'run', 'start']
env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: DATABRICKS_SERVING_ENDPOINT_NAME
    valueFrom: ai-curation-model
  - name: DATABRICKS_VS_INDEX_NAME
    valueFrom: vector-search-index
  - name: MLFLOW_EXPERIMENT_ID
    valueFrom: mlflow-experiment
  - name: DATABRICKS_CATALOG
    value: media_dev
  - name: DATABRICKS_SCHEMA
    value: ott_recommendations
